[package]
authors = ["tko"]
edition = "2018"
name = "cw-zll-std-integration"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
anyhow = { version = "1.0.56" }
cosmwasm-std = { version = "0.16.7" }
cw-multi-test = { git ="https://github.com/CosmWasm/cw-plus.git", tag = "v0.9.2"}
cw-zll-market = { path = "../../contracts/market", features = ["library"] }
cw-zll-liquidity-pool = { path = "../../contracts/liquidity-pool", features = ["library"] }
cw-zll-liquidity-pool-token = { path = "../../contracts/liquidity-pool-token", features = ["library"] }
cw-zll-option-token = { path = "../../contracts/option-token", features = ["library"] }
cw-zll-std-liquidity-pool = { path = "../liquidity-pool" }
cw-zll-std-market = { path = "../market" }
cw20 = "0.9.1"
cw20-base = { version = "0.9.1", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terra-cosmwasm = { version = "2.2.0" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.7" }
